### ISSUE TITLE
Dogs and Cats: demo does not function out of the box on DSVM

### ISSUE THREAD

**Issue by gjwgit** [mlhubber/mlmodels#15]
We need the following to just work

$ ml install dogs-cats
$ ml configure dogs-cats
$ ml demo dogs-cats

**Comment by ZhouFang928** [comment]
ml install dogs-cats-r
ml configure dogs-cats-r
ml demo dogs-cats-r
ml score dogs-cats-r

**Comment by ZhouFang928** [comment]
The dogs-cats model pack is workable. It does not pass the test from other is because of the issue #21

**Comment by gjwgit** [comment]
For reference, the current error on a fresh Azure DSVM is:

Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 1000, 100
Calls: %T>% ... freduce -> <Anonymous> -> cbind -> cbind -> data.frame
Execution halted

**Comment by ZhouFang928** [comment]
It is caused by changing the size of sample image data.

**Comment by ZhouFang928** [comment]
changed the batch_size and steps for predict_generator after changing the size of sample image data. please update pack to mlhub.ai. closed.
