### ISSUE TITLE
CLOTHES RECOMMENDER: Add advise in README to use GPU

### ISSUE THREAD

**Issue by gjwgit** [mlhubber/mlmodels#38]
Perhaps note in the README that a CPU based DSVM will take a long time to run the demo (perhaps provide the expected time with a default DSVM) and be much quicker on a GPU based DSVM (like the DLVM - include the time taken on a default DLVM server).

**Comment by ZhouFang928** [comment]
It does not take a long time to demo/score on sample data by using CPU, since the size of the sample data is very small.

**Comment by ZhouFang928** [comment]
closed
