### ISSUE TITLE
Object-Recognition: score command should locate files from pwd not .mlhub

### ISSUE THREAD

**Issue by gjwgit** [mlhubber/mlmodels#48]
$ ml score object-recognition 
> owl.jpg

Produces file not found error

$ ml score object-recognition 
> ~/owl.jpg

Works fine.

**Comment by simonzhaoms** [comment]
Fix in commit 0012316

**Comment by simonzhaoms** [comment]
Fix in commits  mlhubber/mlmodels@0b57e7d  and debe963
