### ISSUE TITLE
OBJECT RECOGNITION Implement PRINT and DISPLAY commands

### ISSUE THREAD

**Issue by gjwgit** [mlhubber/mlmodels#56]
PRINT will provide a textual summary or information about the model

DISPLAY will pop up a visual display of the model

**Comment by simonzhaoms** [comment]
I didn't find any possible solutions to `print` the model.  So I adapted the code from [AKSDeploymentTutorial/Keras_Tensorflow](https://github.com/Microsoft/AKSDeploymentTutorial/tree/master/Keras_Tensorflow) from scratch using Keras.  Then print out the model by Keras' `summary()` function.  That is different from the original TensorFlow model at [AKSDeploymentTutorial/Tensorflow](https://github.com/Microsoft/AKSDeploymentTutorial/tree/master/Tensorflow), but the overall structures are the same.

As for `display`, it is implemented by using [TensorBoard](https://www.tensorflow.org/guide/graph_viz), which is a simple web service offers visualisation of TensorFlow graph.
