### ISSUE TITLE
Chest Xray

### ISSUE THREAD

**Issue by gjwgit** [mlhubber/mlmodels#6]
Add chest xray model.

https://blogs.technet.microsoft.com/machinelearning/2018/03/07/using-microsoft-ai-to-build-a-lung-disease-prediction-model-using-chest-x-ray-images/

https://healthcareinamerica.us/detecting-diseases-in-chest-x-ray-using-deep-learning-8f454961575f?gi=34a8c4d32031

**Comment by ZhouFang928** [comment]
Are the chest-x-ray data and code publicly published?

**Comment by gjwgit** [comment]
Moved to QUEUE
