### ISSUE TITLE
Rain: Stuck when `ml configure rain`

### ISSUE THREAD

**Issue by simonzhaoms** [mlhubber/mlmodels#60]
$ ml configure rain 
Configuring using '/home/simon/.mlhub/rain/configure.R'...

[sudo] password for simon:

**Comment by simonzhaoms** [comment]
It is stuck when `sudo apt-get install atril` waiting for input of yes or no to install atril.  The message is ignored by https://github.com/mlhubber/mlmodels/blob/0addd156787483da2042b2d77b0ea45b1e0690f1/rain/configure.R#L8

**Comment by gjwgit** [comment]
Fixed.
